name: Validate PR Source Branch

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [ "${{ github.event.pull_request.head.ref }}" != "test" ]; then
            echo "Error: PRs to main can only come from the test branch"
            exit 1
          fi
